### ISSUE TITLE
Error when installing kivy

### ISSUE THREAD

**Issue by sham-a** [jenniferasmar/WeeklyPlans#1]
kivy seems to be installed on my computer since i downloaded the git files, but it is not compatible when working on pycharm and gives me a lot of errors. :( I will try to maybe downgrade my python version (3.8 to 3.7) since kivy is probably not updated to work on python 3.8

**Comment by jenniferasmar** [comment]
Probably the case yes, but if it is installed on your computer, you could try using vscode instead of pycharm? Saw that some people fixed their issue that way 😁 If that doesn't work we'll schedual a meeting 😁

**Comment by sham-a** [comment]
Yeah i can do that! but i think the issue is with kivy not being able to support python 3.8 so im not sure how i could fix it on vscode:/ how did other people fix their issue on vscode?

**Comment by jenniferasmar** [comment]
I am not so sure but you could try coding something simple and running it from your terminal (not pycharm) and if it works than you know pycharm was the problem. So for example you could just code something that shows kivy's version in a class named temp.py and run it in your terminal after navigating to your directory "python3 temp.py"

**Comment by sham-a** [comment]
![Screen Shot 2020-07-21 at 3 55 35 PM](https://user-images.githubusercontent.com/60263286/88100515-a09f7c80-cb6a-11ea-8d39-2cc0513936fd.png)

**Comment by sham-a** [comment]
seems to work! it gives me version of kivy at the bottom "2.0.0rc3"

**Comment by jenniferasmar** [comment]
Yayyy pycharm is the problem!

**Comment by sham-a** [comment]
i am getting another problem now when writing a small program using kivy... I think this is where my python version might be unsupported by kivy. for now ill try installing python extensions and downloading the missing modules to maybe fix this://

![Screen Shot 2020-07-21 at 4 01 31 PM](https://user-images.githubusercontent.com/60263286/88101121-86b26980-cb6b-11ea-9efa-de1d415a7de3.png)

**Comment by jenniferasmar** [comment]
I think you can just run pip install pygame for that one but at least it works!

**Comment by sham-a** [comment]
nope i tried that it doesnt work .. a lot of red lines!

**Comment by sham-a** [comment]
**FIXED** uninstalled python 3.8 along with kivy, then installed python 3.7 and reinstalled kivy for that version
